services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    restart: always
    ports:
      - "3000"
    volumes:
      - wa_app_storages:/app/storages
    environment:
      - APP_PORT=3000
      - APP_ACCOUNT_VALIDATION=false

volumes:
  wa_app_storages: