services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: whatsapp
    restart: always
    volumes:
      - whatsapp:/app/storages
    environment:
      - APP_PORT=3000
      - APP_ACCOUNT_VALIDATION=false

volumes:
  whatsapp: